### ISSUE TITLE
Raster Roadmap

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#200]
### todo, general raster support

---
##### `bigSlider` (aka chart, aka slider, aka animator)
- [x] Set title of current layer in `bigSlider` chart
- [x] Remove blue line in `bigSlider`
- [x] Add event for slider
- [x] Clean up and document `bigSlider` code
- [ ] Move `bigSlider` control to map options? (Need to think about this actually, cause it's connected to cube-layer, etc.)
##### Pull data from raster
- [ ] Designate what data to pull into `bigSlider` depending on layer (currently hardcoded to `allYears`)
- [ ] Support for any time-format in `bigSlider` (eg. minutes, not just days) (@knutole)
- [ ] Change content of slider chart when changing layer (ie. chart should be connected to layer)
- [x] Request yearly data directly from server, querying PostGIS raster.
##### Cube meta
- [ ] "Missing metadata" error when creating empty cube (@knutole)
- [x] better meta in cube dataset list (now only date, text - should add filename, timestamp, etc.) (@knutole)
##### Animation
- [ ] Websocket tiles (@knutole) https://github.com/systemapic/systemapic.js/issues/210
##### Server cache
- [x] Save rendered tiles to disk, and read from disk
- [x] Add md5 for cartocss in tile url (or something), to diff between styles so that cache is correct
##### Add support for _single-raster_ styling
- [x] should be same type as cube styler (stops)
- [x] should update with cartocss on pile-layer and styleJSON on wu-layer (just like other layers)
##### Add support for more stops
- [x] should be possible to add/remove more stops
- [x] cool if opacity could be included in color-picker, instead of input box (find a better colorpicker?)
- [x] PR to support multiple sliders: https://github.com/leongersen/noUiSlider/pull/592
##### Legends
- [x] frano would like to bring some design-ideas on legend for cube-layers
- [x] need to create a legend for raster/cube layers
##### Other, bugs
- [x] Weird bug with clicking "Upload button options" - seems D3.js is doing some large job, and there's almost a full second delay. (Perhaps datalib-refresh triggered on click?) See https://github.com/systemapic/systemapic.js/issues/203.
#### Small bugs on raster styler
- [x] raster styler is open if a layer has been selected before styler is opened
- [ ] something wrong with the way we set `val + 1` stop... we have to look more at this, it doesn't turn out as nice, somehow. (@jorgenevil kan vise deg et eksempel til uka) This has to do with `blur` I think (ie. `raster-scaling: gaussian;`)
- [x] when first stop has opacity 0 and color, and next stop opacity 1 and diff color, the color-scale between them does not take into accoun that halfway the opacity is 0.5 _and the color from first stop_ should be showing. Like here, first stop has opacity 0, but color blue. This is reflected in the rendered raster, but not in the color-scale in the raster.  
  ![screen shot 2016-04-19 at 3 32 29 pm](https://cloud.githubusercontent.com/assets/2197944/14640940/2f3aa5d2-0644-11e6-8443-4b48e3489dea.png)
- [x] Fix bugs with `raster.styler` (eg. carto should be `json`, not `cartocss`.) [this code](https://github.com/systemapic/systemapic.js/blob/rasterStyler2/js/src/chrome/settings/styler.raster.js#L10)
#### Graph bugs
- [x] graph: red triangle not showing on Jan 1st
- [x] when skipping backwards one day at a time across new years, slider doesn't move to far right 
#### Graph design
- [x] Cut some white areas, it takes up a lot of space
- [x] Try some kind of transparent graph? Problems with white area of graph itself, which are not easy to remove. Perhaps just box transparent, but graph itself with white background.
  ![screen shot 2016-04-28 at 12 32 38 am](https://cloud.githubusercontent.com/assets/2197944/14870164/c05b2f24-0cd8-11e6-8827-ad0e878cf85b.png)
- [x] add legends for graph (min/max, avg, current year)  
  ![screen shot 2016-04-28 at 12 31 17 am](https://cloud.githubusercontent.com/assets/2197944/14870149/98ca9922-0cd8-11e6-8823-bb5ee41973c6.png)
#### Minor features
- [x] tabbing in styler list - would be nice to be able to [tab] into the next input
- [x] not possible to dblclick outside of last stop. (not really a bug, but counter-intuitive)
- [ ] set type of stop (exact, linear, etc.) https://github.com/mapnik/mapnik/wiki/RasterColorizer#modes
- [x] add different min/max values than 0-255 (needs server-side checking of range in raster)
- [ ] set blur or no blur (`raster-scaling: gaussian;`) https://github.com/mapbox/carto/blob/master/docs/latest.md#raster Note: blur doesn't work on server right now, for some reason.
- [ ] click on graph to move to that point in time (discuss. bit tricky how to propagate current date.)
#### Areas
- [x] Add areas (nedbørsfelt) as vector
- [x] Query raster based on areas
- [x] Update graph based on data from areas
- [ ] Update graph based on data from custom (drawn) areas
- [ ] etc...
#### Script
- [x] Upload data to existing cube (ie. not create new cube, and don't add to project)
- [ ] Upload data to exisiting project (ie. not create project, but add cube to existing project) 
- [ ] Some simple way to identify format (moment.js compatible)... Worst case, one-liner fn, or just presets which to choose from.

**Comment by knutole** [comment]
See also https://github.com/systemapic/wu/issues/513

**Comment by knutole** [comment]
### Meeting notes

### Todo features
- PRI 1: gui styler. upload i gui.
- dragging slider er viktigst! - live dragging
- play knapp ikke så viktig
- styler i gui
- upload i gui
- scripts til tom rune, eirik
- click on point - get value for all rasters on that pixel
- calculate min/max/avg of custom AREA (nedbørsområde), eller single pixel
- websockets
- knapp for å skru på chart/slider (i leaflet corner)
- se på publish knapp...
- folders på datasets; for prosjekt, custom. drag n drop inn i folders.]
  - highlight hvilke datasets som er aktive
    -tags på datasets, highlight tags, auto-tag dataset with project
- to år med datasett, prøve det først (ift. utregninger av avg/min/max , etc)

### Fremdrift
- tirsdag (gui)
- neste mandag - plot av pixel/gitt område (maske)

---

#### Meeting notes 12. april
- Chart with average only for snow-raster
- Chart for deformation data should only be A-Z (start to finish), not "cyclical" averages over years
- Do averages from actual raster data (not `allYears`, etc)
- Query data per pixel, or per drawn area, or per predefined area (nedbørsfelt)
- Do things _right_ the first time - so that we don't have to waste time un-hardcoding things.
- Legends: `0%-100%` and color scale is enough for snow raster (for now). aka auto-generated, with possiblity of setting 0-255 value to 0-100% value.

**Comment by knutole** [comment]
### Graphs

Two types of graphs (perhaps more later):
1. Cyclical (yearly, for example), with averages, for snow data
2. Linear, from beginning to end of dataset (or range), for demformation data

**Comment by knutole** [comment]
### Masks

Each cube can have a mask, in `TopoJSON` format, which is active for that cube. 
Rasters can also have masks. Masks are stored as `TopoJSON` strings directly on the cube.

**Comment by knutole** [comment]
## TODO pre-thursday
- [ ] add "loading" icon for querying waiting
- [ ] make possible to de-click selected polygon mask
- [x] add legends to graph (min,max,avg)
- [x] fix bug when selecting layer in layermenu twice
- [x] fix bug with 2016 linegraph not showing up
- [ ] bugtest more thoroughly, to make sure no crashes
- [x] update scripts with possibility to add to existing cube/project
- [x] set graph and cube to current date to get data showing on load
- [x] choose nicer colors for masks
- [x] spend wednesday with frano to fix all these things, and tweak last details

**Comment by knutole** [comment]
- [ ] fix cache bug
- [x] fix jumping from 2015 to 2016 etc.
- [x] clean up fetching of averages for `Wu.Graph.Annual`
- [ ] add average-data box to data GUI
- [x] refactor `graph`, `animator`, `cube` in terms of fetching of data
- [ ] verify yearly-graph query results (with eirik)
- [ ] write more API scripts
- [x] bugtest graph/animator/cube
- [ ] bugtest generally
- [ ] clean up queries with proper postgis sql
- [ ] fix general cases: all permutations of queries, masks, layer types
