### ISSUE TITLE
Data Library Roadmap

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#209]
_Beginning of discussion of improved Data Library:_
### Feature requests
- [ ] Folders (for cubes, etc.)
- [ ] Upload pdf's
- [ ] Pagination (if user has a lot of files)
- [ ] Downloadable files for `project` space.

**Comment by franocetinic** [comment]
Add support to upload and download pdf files
